name: Build

on:
  push:
    paths:
      - .github/workflows/build.yml
      - ./src/LaCunaServer.Agent/**
      - ./src/LaCunaServer.Launcher/**

env:
  PROJ_AGENT: ./src/LaCunaServer.Agent/LaCunaServer.Agent.vcxproj
  PROJ_LAUNCHER: ./src/LaCunaServer.Launcher/LaCunaServer.Launcher.csproj

jobs:
  build:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v2

    - name: Setup Dotnet 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.3

    - name: Restore NuGet
      run: dotnet restore ${{env.PROJ_LAUNCHER}}

    - name: Install LaCunaServer.Agent dependencies
      run: |
        vcpkg integrate install
        vcpkg install minhook:x64-windows-static

    - name: Build LaCunaServer.Agent
      run: msbuild /m /p:Configuration=Release /p:Platform=x64 ${{env.PROJ_AGENT}}

    - name: Build LaCunaServer.Launcher
      run: dotnet publish -o ./LaCunaServer-Launcher -r win-x64 --no-self-contained -c Release -v minimal ${{env.PROJ_LAUNCHER}}

    - name: Compress LaCunaServer.Launcher
      run: 7z a launcher.zip ./LaCunaServer-Launcher

    - uses: actions/upload-artifact@v2
      with:
        name: LaCunaServer.Launcher
        path: ./launcher.zip
        retention-days: 14
